repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: detect-private-key
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
        args: ["-shellcheck="]
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        entry: cargo fmt -- --check
        language: system
        types: [rust]
        pass_filenames: false
      - id: clippy
        name: clippy
        entry: cargo clippy -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
